SET timezone='UTC';

-- SEQUENCE
-- TYPE
-- OBJECT
-- SUB_OBJECT
-- RELATIONSHIP

CREATE TABLE mic AS SELECT * FROM read_csv_auto('/home/aaron/Mystuff/python/abacus_v/data/mic/ISO10383_MIC.csv');
-----------------------------------------------------------------------------------------------------------------
-- #TYPE
CREATE SEQUENCE seq_types START 100000000;

-- #RELATIONSHIP
CREATE SEQUENCE seq_relationship START 200000000;

-- #INSTRUMENT
CREATE SEQUENCE seq_instrument START 300000000;

-- #METHODOLOGY
CREATE SEQUENCE seq_methodology START 400000000;

-- #STRATEGY
CREATE SEQUENCE seq_strategy START 500000000;

-- #CLASSIFICATION
CREATE SEQUENCE seq_classification START 600000000;

-- #IDENTIFIER
CREATE SEQUENCE seq_identifier START 700000000;


-----------------------------------------------------------------------------------------------------------------
-- #METHODOLOGY #TYPE
CREATE TABLE methodology_types (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_types'),
    NAME VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #STRATEGY #IDENTIFIER #TYPE
CREATE TABLE strategy_identifier_types (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_types'),
    NAME VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #INSTRUMENT #TYPE
CREATE TABLE instrument_types (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_types'),
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #INSTRUMENT #CLASSIFICATION #TYPE
CREATE TABLE instrument_classification_types (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_types'),
    NAME VARCHAR(255) UNIQUE,
    DESCRIPTION VARCHAR(255),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',  
);

-- #INSTRUMENT #IDENTIFIER #TYPE
CREATE TABLE instrument_identifier_types (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_types'),
    NAME VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #METHODOLOGY
CREATE TABLE methodology (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_methodology'),
    TYPE_ID INTEGER NOT NULL,
    FOREIGN KEY (TYPE_ID) REFERENCES methodology_types(ID),
    FUNCTION_REPO VARCHAR(255),
    FUNCTION_BRANCH VARCHAR(255),
    FUNCTION_FILE VARCHAR(255),
    FUNCTION_NAME VARCHAR(255),
    FUNCTION_DESCRIPTION VARCHAR(255),

    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',   
    
    UNIQUE(TYPE_ID, FUNCTION_REPO, FUNCTION_BRANCH, FUNCTION_FILE, FUNCTION_NAME)
);

-- #STRATEGY
CREATE TABLE strategy (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_strategy'),

    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #INSTRUMENT
CREATE TABLE instruments (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_instrument'),
    TYPE_ID INTEGER NOT NULL,
    FOREIGN KEY (TYPE_ID) REFERENCES instrument_types(ID),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #INSTRUMENT #LIST
CREATE TABLE instrument_list (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_strategy'),
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),

    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #STRATEGY #IDENTIFIER
CREATE TABLE strategy_identifier (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_strategy'),
    TYPE_ID INTEGER NOT NULL,
    FOREIGN KEY (TYPE_ID) REFERENCES strategy_identifier_types(ID),
    VALUE VARCHAR(255) NOT NULL,
   
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',   
     UNIQUE (TYPE_ID, VALUE) 
);

-- #INSTRUMENT #IDENTIFIER
CREATE TABLE instrument_identifier (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_identifier'),
    TYPE_ID INTEGER NOT NULL,
    FOREIGN KEY (TYPE_ID) REFERENCES instrument_identifier_types(ID),
    VALUE VARCHAR(255) NOT NULL,
    UNIQUE (TYPE_ID, VALUE),

    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',    
);

-- #INSTRUMENT #CLASSIFICATION
CREATE TABLE instrument_classifications (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_classification'),
    INSTRUMENT_CLASSIFICATION_TYPE_ID INTEGER NOT NULL,
    FOREIGN KEY (INSTRUMENT_CLASSIFICATION_TYPE_ID) REFERENCES instrument_classification_types(ID),
    VALUE VARCHAR(255) NOT NULL,
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',  

    -- Only one classification per instrument per classification type per valid from date
    UNIQUE (INSTRUMENT_CLASSIFICATION_TYPE_ID, VALUE, VALID_FROM)
);

-- #STRATEGY #IDENTIFIER #RELATIONSHIP
CREATE TABLE strategy_identifier_relationship (
    STRATEGY_ID INTEGER NOT NULL,
    FOREIGN KEY (STRATEGY_ID) REFERENCES strategy(ID),
    STRATEGY_IDENTIFIER_ID INTEGER NOT NULL,    
    FOREIGN KEY (STRATEGY_IDENTIFIER_ID) REFERENCES strategy_identifier(ID),
    TYPE VARCHAR(255) DEFAULT 'REFERENCES',    
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',  

    -- Only one classification per instrument per classification type per valid from date
    UNIQUE (STRATEGY_ID, STRATEGY_IDENTIFIER_ID, VALID_FROM)
);

-- #INSTRUMENT #IDENTIFIER #RELATIONSHIP
CREATE TABLE instrument_identifier_relationship (
    INSTRUMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES instruments(ID),
    INSTRUMENT_IDENTIFIER_ID INTEGER NOT NULL,    
    FOREIGN KEY (INSTRUMENT_IDENTIFIER_ID) REFERENCES instrument_identifier(ID),
    TYPE VARCHAR(255) DEFAULT 'REFERENCES',    
    UNIQUE (INSTRUMENT_ID, INSTRUMENT_IDENTIFIER_ID, VALID_FROM),    

    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',
);

-- #INSTRUMENT #CLASSIFICATION #RELATIONSNHIP
CREATE TABLE instrument_classification_relationship (
    INSTRUMENT_ID INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES instruments(ID),
    CLASSIFICATION_ID INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (CLASSIFICATION_ID) REFERENCES instrument_classifications(ID),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',  

    UNIQUE (INSTRUMENT_ID, CLASSIFICATION_ID, VALID_FROM)
);

-- #STRATEGY #METHODOLOGY #RELATIONSHIP
CREATE TABLE strategy_methodology_relationship (
    ID INTEGER PRIMARY KEY DEFAULT nextval('seq_relationship'),
    STRATEGY_ID INTEGER NOT NULL,
    FOREIGN KEY (STRATEGY_ID) REFERENCES strategy(ID),
    METHODOLOGY_ID INTEGER NOT NULL,
    FOREIGN KEY (METHODOLOGY_ID) REFERENCES methodology(ID),
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',  

    UNIQUE (STRATEGY_ID, METHODOLOGY_ID, VALID_FROM)
);

-- #INSTRUMENT #MARKET #RELATIONSHIP
CREATE TABLE instrument_market_relationship (
    INSTRUMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES instrument(ID),
    MIC INTEGER NOT NULL,
    FOREIGN KEY (MIC) REFERENCES mic(MIC),
    TYPE VARCHAR(255) DEFAULT 'REFERENCES',
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',    
);

-- #INSTRUMENT #LIST #RELATIONSHIP
CREATE TABLE instrument_list_relationship (
    INSTRUMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (INSTRUMENT_ID) REFERENCES instrument(ID),
    LIST_ID INTEGER NOT NULL,
    FOREIGN KEY (LIST_ID) REFERENCES instrument_list(ID),
    TYPE VARCHAR(255) DEFAULT 'REFERENCES',
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',    
);

-- INSTRUMENT #LIST #STRATEGY #RELATIONSHIP
CREATE TABLE instrument_list_strategy_relationship (
    LIST_ID INTEGER NOT NULL,
    FOREIGN KEY (LIST_ID) REFERENCES instrument_list(ID),
    STRATEGY_ID INTEGER NOT NULL,
    FOREIGN KEY (STRATEGY_ID) REFERENCES strategy(ID),
    TYPE VARCHAR(255) DEFAULT 'REFERENCES',
    
    VALID_FROM DATE DEFAULT CURRENT_DATE,
    VALID_TO DATE DEFAULT '3000-12-31',
    UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) DEFAULT 'System',
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) DEFAULT 'System',    
);

-- VIEWS ---------------------------------------------------------------------
CREATE VIEW view_strategy_identifiers AS (
SELECT s.ID, sid.NAME, si.VALUE
FROM strategy s
JOIN strategy_identifier_relationship sr ON s.ID=sr.STRATEGY_ID
JOIN strategy_identifier si ON sr.STRATEGY_IDENTIFIER_ID=si.ID 
JOIN strategy_identifier_types sid on si.TYPE_ID=sid.ID
WHERE s.VALID_FROM<=current_date() AND s.VALID_TO>=current_date()
AND sr.VALID_FROM<=current_date() AND sr.VALID_TO>=current_date()
AND si.VALID_FROM<=current_date() AND si.VALID_TO>=current_date()
);

CREATE VIEW view_strategy_methodology AS (
SELECT s.ID, mt.NAME, m.FUNCTION_REPO, m.FUNCTION_BRANCH, m.FUNCTION_FILE, m.FUNCTION_NAME
FROM strategy s
JOIN strategy_methodology_relationship smr ON s.ID=smr.STRATEGY_ID
JOIN methodology m ON smr.METHODOLOGY_ID=m.ID
JOIN methodology_types mt ON m.TYPE_ID=mt.ID
WHERE s.VALID_FROM<=current_date() AND s.VALID_TO>=current_date()
AND smr.VALID_FROM<=current_date() AND smr.VALID_TO>=current_date()
AND mt.VALID_FROM<=current_date() AND mt.VALID_TO>=current_date()
);

-- SEED DATA ------------------------------------------------------------------
INSERT INTO strategy_types (NAME, DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('Strategy', 'Strategy', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO methodology (TYPE_ID, FUNCTION_REPO, FUNCTION_BRANCH, FUNCTION_FILE, FUNCTION_NAME, FUNCTION_DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (1000001, 'https://github.com/TrinaryLLC/abacus', 'main', 'strategy.py', 'strategy', 'Strategy', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO methodology_types (NAME, DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('Methodology', 'Methodology', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instruments (TYPE_ID, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (1000000, CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_types (NAME, DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('Instrument', 'Instrument', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_identifier_types (NAME, DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('Identifier', 'Identifier', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_identifier (TYPE_ID, VALUE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (1000000, 'ID', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_identifier_relationship (INSTRUMENT_ID, INSTRUMENT_IDENTIFIER_ID, TYPE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (2000000, 1000000, 'REFERENCES', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_market_relationship (TYPE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('REFERENCES', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_classification_types (NAME, DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('Classification', 'Classification', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO instrument_classifications (INSTRUMENT_ID, INSTRUMENT_CLASSIFICATION_TYPE_ID, VALUE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (2000000, 1000000, 'Classification', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');    
INSERT INTO instrument_classification_relationship (INSTRUMENT_ID, CLASSIFICATION_ID, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (2000000, 1000000, CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO strategy_methodology_relationship (STRATEGY_ID, METHODOLOGY_ID, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (4000000, 1000000, CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO strategy_identifier_relationship (STRATEGY_ID, STRATEGY_IDENTIFIER_ID, TYPE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES(4000000, 4000003, 'REFERENCES', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO strategy_identifier (TYPE_ID, VALUE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (1000000, 'ID', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
-- Orphaned identifer : Not linked to a strategy. Will not populate in view
INSERT INTO strategy_identifier (TYPE_ID, VALUE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (1000000, 'TEST_NAME', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO strategy_identifier_types (NAME, DESCRIPTION, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES ('Identifier', 'Identifier', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO strategy_identifier_relationship (STRATEGY_ID, STRATEGY_IDENTIFIER_ID, TYPE, VALID_FROM, VALID_TO, UPDATED, UPDATED_BY, CREATED, CREATED_BY) VALUES (1000000, 1000000, 'REFERENCES', CURRENT_DATE, '3000-12-31', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, 'System');
INSERT INTO strategy (VALID_FROM) VALUES (CURRENT_DATE);